# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MR8KqIvoWdPMOML_FWceapdry0RH9t4k
"""

!pip install flickrapi
import flickrapi
import pandas as pd
import time

# -----------------------------
# 1. Flickr API key
# -----------------------------
API_KEY = ""
API_SECRET = ""

flickr = flickrapi.FlickrAPI(API_KEY, API_SECRET, format='parsed-json')

# -----------------------------
# 2. Camden bounding box
# west, south, east, north
# -----------------------------
bbox = "-0.213,51.528,-0.110,51.572"

# -----------------------------
# 3. Search photos in Camden
# -----------------------------
photos_data = []
page = 1
per_page = 50
max_pages = 3

while page <= max_pages:
    response = flickr.photos.search(
        bbox=bbox,
        min_taken_date="2020-01-01",
        extras="description,tags,geo,date_taken,owner_name",
        has_geo=1,
        per_page=per_page,
        page=page,
        content_type=1,
        media="photos",
        sort="relevance"
    )

    photos = response["photos"]["photo"]
    if not photos:
        break

    for p in photos:
        photo_id = p.get("id")
        title = p.get("title", "")
        description = p.get("description", {}).get("_content", "")
        tags = p.get("tags", "")
        lat = p.get("latitude", "")
        lon = p.get("longitude", "")
        date_taken = p.get("datetaken", "")
        owner_name = p.get("ownername", "")

        # -----------------------------
        # 4. Get comments for each photo
        # -----------------------------
        comments_text = []
        try:
            comments_response = flickr.photos.comments.getList(photo_id=photo_id)
            comments = comments_response.get("comments", {}).get("comment", [])
            for c in comments:
                text = c.get("_content", "").strip()
                if text:
                    comments_text.append(text)
        except Exception as e:
            print(f"Could not get comments for photo {photo_id}: {e}")

        photos_data.append({
            "photo_id": photo_id,
            "title": title,
            "description": description,
            "tags": tags,
            "latitude": lat,
            "longitude": lon,
            "date_taken": date_taken,
            "owner_name": owner_name,
            "comments": " | ".join(comments_text)
        })

        time.sleep(0.5)

    print(f"Finished page {page}")
    page += 1

# -----------------------------
# 5. Save to CSV
# -----------------------------
df = pd.DataFrame(photos_data)
df.to_csv("camden_flickr_comments.csv", index=False, encoding="utf-8-sig")

print("Done. Saved as camden_flickr_comments.csv")
print(df.head())
